source 'https://rubygems.org'
ruby '2.2.3'
gem 'rails', '4.2.4'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'paperclip', '~> 4.3'
group :development, :test do
  gem 'byebug'
end
group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
gem 'bootstrap-sass'
gem 'devise'
gem 'pundit'
gem 'therubyracer', :platform=>:ruby
gem 'upmin-admin'
group :development do
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
end
group :development, :test do
  gem 'sqlite3'
end
group :production do
  gem 'pg'
  gem 'unicorn'
  gem 'rails_12factor'
end

gem 'hirb'
gem 'ratyrate'
gem 'will_paginate'
